export const FETCH_CONTACT = "FETCH_CONTACT";
export const FETCH_CONTACTS = "FETCH_CONTACTS";
export const CREATE_CONTACT = "CREATE_CONTACT";
export const EDIT_CONTACT = "EDIT_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";

export const UPDATE_CLICKED_PHOTO_URI = "UPDATE_CLICKED_PHOTO_URI";